services:
  backend:
    container_name: "backend-gym"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "gym"
      DB_PORT: 3306
      DB_HOST: "host.docker.internal"
